# Generated by Django 2.2.6 on 2019-11-17 20:01

from django.db import migrations, models
import policies.models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.FileField(upload_to=policies.models.upload_site_img),
        ),
    ]
