# Generated by Django 2.2.6 on 2019-11-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slots',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
