# Generated by Django 2.2.6 on 2019-12-11 02:17

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20191211_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(upload_to=activities.models.upload_site_img),
        ),
    ]
