# Generated by Django 2.2.6 on 2019-12-11 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20191211_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.AddField(
            model_name='activity',
            name='week',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
