# Generated by Django 2.2.6 on 2019-12-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20191211_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
    ]
