# Generated by Django 2.2.6 on 2019-11-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': '1 - Staff Roles',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.StaffRole')),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': '2 - Staff Profiles',
            },
        ),
    ]
