# Generated by Django 2.2.6 on 2019-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(default='egweg'),
            preserve_default=False,
        ),
    ]
