# Generated by Django 2.2.6 on 2019-11-09 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='staff/images'),
            preserve_default=False,
        ),
    ]
