# Generated by Django 2.2.6 on 2019-11-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='firt_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='k', max_length=300),
            preserve_default=False,
        ),
    ]
