# Generated by Django 2.2.6 on 2019-11-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20191109_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
