# Generated by Django 2.2.6 on 2019-11-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffrole_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
