# Generated by Django 2.2.6 on 2019-11-12 13:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20191109_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
    ]
