# Generated by Django 2.2.6 on 2019-11-15 16:42

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20191112_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.ImageField(upload_to=staff.models.upload_site_img),
        ),
    ]
