# Generated by Django 2.2.6 on 2019-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20191115_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rank',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
