# Generated by Django 2.2.6 on 2019-12-11 02:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staff_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrusteeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=300)),
                ('rank', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Trustee Role',
                'verbose_name_plural': '4 - Trustee Roles',
            },
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('rank', models.IntegerField()),
                ('bio', tinymce.models.HTMLField()),
                ('img', models.ImageField(upload_to='')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.StaffRole')),
            ],
            options={
                'verbose_name': 'Trustee Profile',
                'verbose_name_plural': '3 - Trustee Profiles',
            },
        ),
    ]
