# Generated by Django 2.2.6 on 2019-12-11 02:47

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_remove_trustee_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustee',
            name='img',
            field=models.ImageField(default='aawvv', upload_to=staff.models.upload_site_img),
            preserve_default=False,
        ),
    ]
