# Generated by Django 2.2.6 on 2019-12-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_trustee_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustee',
            name='company',
            field=models.CharField(default='jms', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trustee',
            name='link',
            field=models.CharField(default='https://www.aavaev.co.uk', max_length=500),
            preserve_default=False,
        ),
    ]
