# Generated by Django 2.2.6 on 2019-11-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Contact Detail',
                'verbose_name_plural': '2 - Contact Details',
            },
        ),
        migrations.CreateModel(
            name='OpeningDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Opening Day',
                'verbose_name_plural': '1 - Opening Days',
            },
        ),
    ]
