# Generated by Django 2.2.6 on 2019-11-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=14)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': '3 - Contact Requests',
            },
        ),
    ]
