# Generated by Django 2.2.6 on 2019-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Donations',
                'verbose_name_plural': '1 - Donations',
            },
        ),
    ]
