# Generated by Django 2.2.6 on 2019-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
