# Generated by Django 2.2.6 on 2019-11-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='ll@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
