# Generated by Django 2.2.6 on 2019-11-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=6),
        ),
    ]
