# Generated by Django 2.2.6 on 2019-11-15 11:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20191114_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Donations Text',
                'verbose_name_plural': '1 - Donations Text',
            },
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donations', 'verbose_name_plural': '2 - Donations'},
        ),
    ]
