# Generated by Django 2.2.6 on 2019-11-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homelandingtext',
            options={'verbose_name': ('Landing Text',), 'verbose_name_plural': 'Landing Text'},
        ),
    ]
