# Generated by Django 2.2.6 on 2019-11-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191108_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homelandingtext',
            options={},
        ),
    ]
