# Generated by Django 2.2.6 on 2019-11-08 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191108_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
