# Generated by Django 2.2.6 on 2019-11-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_example'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homelandingtext',
            options={'verbose_name': 'Landing Text', 'verbose_name_plural': 'Landing Text'},
        ),
    ]
