# Generated by Django 2.2.6 on 2019-11-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homeabouttext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeabouttext',
            options={'verbose_name': '2 - About Text', 'verbose_name_plural': '2 - About Text'},
        ),
        migrations.AlterModelOptions(
            name='homelandingtext',
            options={'verbose_name': '1 - Landing Text', 'verbose_name_plural': '1 - Landing Text'},
        ),
    ]
