# Generated by Django 2.2.6 on 2019-11-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191108_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homelandingtext',
            options={'verbose_name': 'Landing Text', 'verbose_name_plural': '1 - Landing Text'},
        ),
    ]
