# Generated by Django 2.2.6 on 2019-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191108_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='sponsers')),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name': 'Sponser',
                'verbose_name_plural': '1 - Sponsers',
            },
        ),
    ]
