# Generated by Django 2.2.6 on 2019-11-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sponser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponser',
            options={'verbose_name': 'Sponser', 'verbose_name_plural': '3 - Sponsers'},
        ),
    ]
