# Generated by Django 2.2.6 on 2019-11-12 13:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191112_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabouttext',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
