# Generated by Django 2.2.6 on 2019-11-15 16:42

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191112_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='img',
            field=models.ImageField(upload_to=home.models.upload_site_img),
        ),
    ]
