# Generated by Django 2.2.6 on 2019-12-11 03:34

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191115_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=home.models.upload_site_img)),
                ('rank', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Home Image',
                'verbose_name_plural': '3 - Home Images',
            },
        ),
        migrations.AlterModelOptions(
            name='sponser',
            options={'verbose_name': 'Sponser', 'verbose_name_plural': '4 - Sponsers'},
        ),
    ]
