# Generated by Django 2.2.6 on 2019-11-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationtext',
            options={'verbose_name': 'Information Text', 'verbose_name_plural': '1 - Information Text'},
        ),
    ]
