# Generated by Django 2.2.6 on 2019-11-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20191108_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This will not be displayed this is for your reference', max_length=300)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Sticky Note',
                'verbose_name_plural': '2 - Sticky Notes',
            },
        ),
    ]
