# Generated by Django 2.2.6 on 2019-11-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20191108_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationtext',
            name='text',
        ),
    ]
